#include <algorithm>
#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include "conv_engine.h"
// Real per-layer data (REAL_WEIGHTS_PLAN.md step 7) - generated by
// python/real_layers.py, NOT hand-written. See run_real_layer() below and
// this header's own top comment for why it's embedded rather than read
// from python/layerNN_*.bin at C-sim runtime.
#include "real_layers_data.h"

// Full m_axi interface depths - must match conv_engine.cpp's `#pragma HLS
// INTERFACE m_axi ... depth=...` expressions exactly. C/RTL co-simulation
// builds its RTL bus-functional-model's memory image from the host pointer
// using this depth, regardless of how much of it a given call's actual
// img_h/img_w/in_ch/out_ch/k dimensions use - passing a host array smaller
// than `depth` makes cosim read past the end of the allocation (SIGSEGV
// during ENTER_WRAPC; see TROUBLESHOOTING.md's cosim entry). Plain C-sim
// never uses `depth` at all, so this was never needed until cosim was
// attempted.
// ifmap/weights depths now scale with MAX_TOTAL_IN_CH (1024), not MAX_IN_CH
// (128) - see conv_engine.cpp's matching m_axi depth= pragmas for why
// (input-channel tiling: on-chip buffers stay MAX_IN_CH-wide, but the DDR
// arrays they're tiled slices of must be addressable across a layer's real
// total in_ch).
static const size_t IFMAP_DEPTH   = (size_t)MAX_IMG_W * MAX_IMG_W * MAX_TOTAL_IN_CH;

// ---- PACK4 testbench helpers ----------------------------------------------
// conv_engine's `ifmap` port is now pack4_t (4 consecutive NHWC channels per
// 32-bit beat, see HW/pack4.h), so the tb's ifmap buffer is allocated and
// passed in WORDS. Every other port is unchanged.
//
// The reference_conv() model and all the golden arrays stay entirely
// int8_t-based and completely unaware of the packing - that is what makes a
// PASS here evidence the packing is bit-exact, rather than evidence that
// both sides share the same packing bug.
//
// IFMAP_DEPTH above stays in ELEMENTS so it still reads as the same
// img/ch bound product the engine's depth= pragma uses; pack4_words()
// converts at each point of use.
static inline size_t pack4_words(size_t elems) {
    return (elems + PACK4_LANES - 1) / PACK4_LANES;
}

// Flat int8 element index -> (word, lane), matching pack4.h's little-endian
// lane order: lane 0 is the lowest channel index and the low byte. This is
// the mapping the DDR byte layout already had, which is why no PS-side
// repacking is needed in real hardware - it is spelled out here only
// because the tb holds its golden data in a separate int8_t array.
static inline void pack4_put(std::vector<pack4_t> &buf, size_t elem_idx, int8_t v) {
    pack4_set(buf[elem_idx / PACK4_LANES], (unsigned)(elem_idx % PACK4_LANES), (ap_int<8>)v);
}
static const size_t WEIGHTS_DEPTH = (size_t)MAX_OUT_CH * MAX_TOTAL_IN_CH * MAX_K * MAX_K;
static const size_t BIAS_DEPTH    = (size_t)MAX_OUT_CH;
static const size_t OFMAP_DEPTH   = (size_t)MAX_IMG_W * MAX_IMG_W * MAX_OUT_CH;
// accum is [out_h][out_w][PE_OC], not [out_h][out_w][out_ch] - see
// conv_engine.h's note on the `accum` parameter for why.
static const size_t ACCUM_DEPTH   = (size_t)MAX_IMG_W * MAX_IMG_W * PE_OC;

// ---------------------------------------------------------------------------
// C-simulation testbench for conv_engine.
//
// Unlike conv_layer1_tb.cpp (which drives ONE fixed, compile-time-sized
// layer), this testbench exists specifically to prove the engine's core
// claim: that it produces correct output across DIFFERENT runtime
// geometries, not just the one shape it happens to be compiled for. It runs
// eleven deliberately different configs (A-K, see main() below) through the
// same conv_engine() call, each exercising a different edge case (multi-tile
// output-channel tiling, k=1, minimal channel counts, the MAX_IN_CH boundary,
// a non-multiple-of-TR reduction, non-square images, a pe-pair straddling
// the out_ch boundary after a preceding full tile (config H, added for this
// project's INT8 DSP-packing experiment), and - configs I/J/K, added once
// the real network showed input-channel tiling was needed, see
// conv_engine.h - multi-pass ic_tile coverage with and without a remainder,
// and both oc_tile/ic_tile tiling happening at once), plus one dedicated
// "config-A-cosim" repeat of config-A sized for C/RTL
// co-simulation specifically (see run_config()'s pad_to_full_depth
// parameter). Before the config sweep, main() also runs
// pack_unpack_selftest_fast() (exhaustive, plain-int) and
// pack_unpack_selftest_ap_int_sample() (a smaller ap_int-typed confirmation
// pass) - see the comment above their definitions for why it's split into
// two rather than one.
//
// Sizes are intentionally small (not the real 416x416 Phase 1 input) - this
// suite is about proving runtime-parameterization correctness quickly, not
// about exercising the real network's actual layer sizes. The real sizes
// only matter once this passes and the design moves to hardware bring-up
// (SW/network_run.c) on actual silicon, per hls_study_plan.md's phased
// approach. Only "config-A-cosim" pays the cost of full-m_axi-depth host
// buffers (IFMAP_DEPTH etc. below) - the other 8 configs stay at their
// actual, small per-config sizes, since plain C-sim never reads `depth` at
// all and paying that cost on every config (tried first) made ordinary
// C-sim dramatically slower for no benefit to it.
// ---------------------------------------------------------------------------

static int8_t clamp_i8(int64_t v) {
    if (v > 127)  return 127;
    if (v < -128) return -128;
    return (int8_t)v;
}

// round(x / 2^s), ties away from zero - plain int64_t implementation of the
// same RTL_HANDOFF_KO.md section 5 formula conv_engine.cpp's round_shift()
// implements in ap_int<64>. Written independently here (not calling into
// conv_engine.cpp, whose round_shift()/apply_activation() are file-local
// static functions anyway) so a bug in one has no way to silently agree
// with the other - same "no shared code path" reasoning this function's
// caller already documents for the conv math itself.
static int64_t round_shift_ref(int64_t x, unsigned s) {
    if (s == 0) return x;
    int64_t half = (int64_t)1 << (s - 1);
    return (x >= 0) ? ((x + half) >> s) : -(((-x) + half) >> s);
}

// Independent reference convolution - deliberately NOT sharing any code path
// with conv_engine.cpp (no shared window/line-buffer structure), so a bug in
// conv_engine's raster-scan indexing has no way to silently agree with this.
static void reference_conv(
    const std::vector<int8_t> &x, const std::vector<int8_t> &w, const std::vector<int32_t> &b,
    std::vector<int8_t> &out,
    unsigned img_h, unsigned img_w, unsigned in_ch, unsigned out_ch,
    unsigned k, unsigned pad,
    bool leaky_relu_enable, int32_t requant_multiplier, unsigned requant_shift
) {
    unsigned out_h = img_h + 2 * pad - k + 1;
    unsigned out_w = img_w + 2 * pad - k + 1;
    out.assign((size_t)out_h * out_w * out_ch, 0);

    for (unsigned r = 0; r < out_h; r++) {
        for (unsigned c = 0; c < out_w; c++) {
            for (unsigned oc = 0; oc < out_ch; oc++) {
                int64_t acc = b[oc];
                for (unsigned ic = 0; ic < in_ch; ic++) {
                    for (unsigned ky = 0; ky < k; ky++) {
                        for (unsigned kx = 0; kx < k; kx++) {
                            int in_r = (int)r + (int)ky - (int)pad;
                            int in_c = (int)c + (int)kx - (int)pad;
                            int8_t px = 0;
                            if (in_r >= 0 && in_r < (int)img_h &&
                                in_c >= 0 && in_c < (int)img_w) {
                                px = x[((size_t)in_r * img_w + in_c) * in_ch + ic];
                            }
                            unsigned w_idx = ((oc * in_ch + ic) * k + ky) * k + kx;
                            acc += (int64_t)px * (int64_t)w[w_idx];
                        }
                    }
                }
                // RTL_HANDOFF_KO.md section 5, in order: LeakyReLU(13/128) on
                // the raw accumulator (only if negative), THEN per-layer
                // requantize, THEN saturate - NOT the old placeholder
                // "acc>=0 ? acc : acc>>3" this replaces.
                if (leaky_relu_enable && acc < 0) {
                    acc = round_shift_ref(acc * 13, 7);
                }
                int64_t scaled = acc * (int64_t)requant_multiplier;
                int64_t activated = round_shift_ref(scaled, requant_shift);
                out[((size_t)r * out_w + c) * out_ch + oc] = clamp_i8(activated);
            }
        }
    }
}

// Self-test of the INT8 DSP-packing primitive (conv_engine.h's
// packed_weight_t, and the pack/unpack math in conv_engine.cpp's
// load_weight_tile()/scan_and_compute()), run in isolation before the
// config sweep below. RESOURCE_BUDGET.md §5 flags this exact technique as
// "getting it wrong silently produces wrong math rather than a synthesis
// error" - split into two passes rather than one, for a reason found the
// hard way (see below).
//
// Pass 1 (pack_unpack_selftest_fast): exhaustively brute-forces ALL
// 256*256*256 = 16,777,216 (X, Y_lo, Y_hi) triples, but using PLAIN native
// integer arithmetic that emulates the exact same mask/shift/sign-extend
// operations, not real ap_int types. This is what actually matters for
// correctness - it's what caught the original missing "+1 carry when the
// low field's sign bit is set" bug, which was a math error, not an
// ap_int-specific one. It runs in well under a second.
//
// Pass 2 (pack_unpack_selftest_ap_int_sample): confirms the REAL ap_int/HLS
// types (packed_weight_t, .range(), signed shifts, casts) behave exactly
// like pass 1's plain-int model - but only over a much smaller, deliberately
// chosen set (all sign/magnitude corner cases + a fixed reproducible random
// sample), not the full 16.7M. Running the full exhaustive sweep through
// real ap_int arithmetic was tried first and made C-sim impractically
// slow (looked "stuck") - ap_int's arbitrary-precision simulation model
// pays real per-operation overhead that a native int does not, and at
// 16.7M iterations that overhead compounds into minutes-to-hours instead
// of seconds. This pass exists only to catch an ap_int-semantics surprise
// (e.g. if `.range()`'s sign-reinterpretation behaved differently than
// assumed) that pass 1 - being plain-int - could not catch on its own.
//
// Both are pure C++ host-side tests - never synthesized, no __SYNTHESIS__
// guard needed.
static void pack_unpack_selftest_fast() {
    for (int xi = -128; xi <= 127; xi++) {
        for (int yhi = -128; yhi <= 127; yhi++) {
            for (int ylo = -128; ylo <= 127; ylo++) {
                uint32_t y_lo_biased = (uint8_t)ylo ^ 0x80u;
                int64_t packed = ((int64_t)yhi << 16) | y_lo_biased;
                int64_t product = (int64_t)xi * packed;

                int32_t low16 = (int32_t)(product & 0xFFFF);
                if (low16 & 0x8000) low16 -= 0x10000; // sign-extend, matches ap_int<16>

                int64_t contrib_hi = product >> 16; // matches ap_int's arithmetic shift
                if (low16 < 0) contrib_hi += 1;      // the carry correction under test
                int64_t contrib_lo = low16 - ((int64_t)xi << 7);

                if (contrib_hi != (int64_t)xi * yhi || contrib_lo != (int64_t)xi * ylo) {
                    printf("pack_unpack_selftest_fast FAIL: x=%d y_lo=%d y_hi=%d "
                           "-> contrib_lo=%lld (want %d) contrib_hi=%lld (want %d)\n",
                           xi, ylo, yhi, (long long)contrib_lo, xi * ylo,
                           (long long)contrib_hi, xi * yhi);
                    assert(false && "packed MAC split algorithm mismatch");
                }
            }
        }
    }
    printf("pack_unpack_selftest_fast: 16,777,216 combinations (plain-int model) PASS\n");
}

static void pack_unpack_selftest_ap_int_sample() {
    auto check_one = [](int xi, int ylo, int yhi) {
        act_t x = (act_t)xi;
        weight_t y_hi = (weight_t)yhi;
        weight_t y_lo = (weight_t)ylo;

        // Mirrors load_weight_tile()'s pack step exactly.
        ap_uint<8> y_lo_biased = (ap_uint<8>)y_lo ^ (ap_uint<8>)0x80;
        packed_weight_t packed =
            (((ap_int<25>)y_hi) << 16) + (ap_int<25>)y_lo_biased;

        // Mirrors scan_and_compute()'s MAC_KX unpack step exactly, including
        // the +1 carry correction on contrib_hi.
        ap_int<33> product = x * packed;
        ap_int<16> l_signed = product.range(15, 0);
        accum_t contrib_hi = (accum_t)(product >> 16);
        if (l_signed < 0) {
            contrib_hi += 1;
        }
        accum_t contrib_lo = (accum_t)l_signed - ((accum_t)x << 7);

        if (contrib_hi != xi * yhi || contrib_lo != xi * ylo) {
            printf("pack_unpack_selftest_ap_int_sample FAIL: x=%d y_lo=%d y_hi=%d "
                   "-> contrib_lo=%d (want %d) contrib_hi=%d (want %d)\n",
                   xi, ylo, yhi, (int)contrib_lo, xi * ylo,
                   (int)contrib_hi, xi * yhi);
            assert(false && "packed MAC split ap_int-type mismatch");
        }
    };

    // All sign/magnitude corner cases: 6*6*6 = 216 combinations, covering
    // every boundary the split logic's correctness actually depends on
    // (most negative, most positive, +-1, zero).
    const int corners[] = {-128, -127, -1, 0, 1, 127};
    for (int xi : corners)
        for (int yhi : corners)
            for (int ylo : corners)
                check_one(xi, ylo, yhi);

    // Fixed, reproducible pseudo-random sample across the full range, to
    // catch anything the hand-picked corners above might miss - small
    // enough to stay fast even at ap_int's simulation speed.
    srand(12345);
    for (int i = 0; i < 20000; i++) {
        int xi  = (rand() % 256) - 128;
        int ylo = (rand() % 256) - 128;
        int yhi = (rand() % 256) - 128;
        check_one(xi, ylo, yhi);
    }

    printf("pack_unpack_selftest_ap_int_sample: 216 corner + 20,000 random "
           "combinations (real ap_int types) PASS\n");
}

// Runs one config through conv_engine() and checks it against reference_conv().
// Returns 0 on PASS, 1 on FAIL (mirrors conv_layer1_tb.cpp's convention).
//
// `pad_to_full_depth` (default false): when true, allocates the four
// host-side arrays passed to conv_engine() at the FULL m_axi depth
// (IFMAP_DEPTH etc. above) instead of this config's actual (much smaller)
// dimensions - only actually needed for C/RTL co-simulation (see the
// comment on those constants). Defaults to false because plain C-sim
// never reads `depth` at all, and unconditionally paying for ~200M-element
// allocations across all 8 configs (tried first) made ordinary C-sim
// dramatically slower - the same category of problem as the exhaustive
// ap_int self-test's slowdown (TROUBLESHOOTING.md §7), just ~100x more
// ap_int-construction work (1.6 billion elements across 8 configs vs. that
// entry's 16.7 million). Only the one dedicated cosim config in main()
// passes true - cosim's job is checking the tool's C-to-RTL translation
// fidelity on a representative case, not re-proving algorithm correctness
// across edge cases, which the other 8 configs already do exhaustively via
// fast, small-buffer C-sim.
static int run_config(
    const char *name,
    unsigned img_h, unsigned img_w, unsigned in_ch, unsigned out_ch,
    unsigned k, unsigned pad, unsigned seed,
    bool leaky_relu_enable, int32_t requant_multiplier, unsigned requant_shift,
    bool pad_to_full_depth = false
) {
    srand(seed);

    std::vector<int8_t>  x((size_t)img_h * img_w * in_ch);
    std::vector<int8_t>  w((size_t)out_ch * in_ch * k * k);
    std::vector<int32_t> b(out_ch);

    for (auto &v : x) v = (int8_t)((rand() % 41) - 20);
    for (auto &v : w) v = (int8_t)((rand() % 11) - 5);
    // Wider range than weight_t's [-5,4] above - bias is now signed INT32
    // (bias_t, matching the golden model's bias.bin), so this exercises
    // values a plain INT8 bias never could.
    for (auto &v : b) v = (int32_t)((rand() % 2001) - 1000);

    std::vector<int8_t> ref_out;
    reference_conv(x, w, b, ref_out, img_h, img_w, in_ch, out_ch, k, pad,
                   leaky_relu_enable, requant_multiplier, requant_shift);

    unsigned out_h = img_h + 2 * pad - k + 1;
    unsigned out_w = img_w + 2 * pad - k + 1;

    size_t ifmap_size   = pad_to_full_depth ? IFMAP_DEPTH   : x.size();
    size_t weights_size = pad_to_full_depth ? WEIGHTS_DEPTH : w.size();
    size_t bias_size    = pad_to_full_depth ? BIAS_DEPTH    : b.size();
    size_t ofmap_size   = pad_to_full_depth ? OFMAP_DEPTH   : (size_t)out_h * out_w * out_ch;
    // accum only needs [out_h][out_w][PE_OC] elements, never [out_h][out_w]
    // [out_ch] - true regardless of pad_to_full_depth, since conv_engine()
    // itself never indexes accum by more than PE_OC channels (see its
    // m_axi depth= pragma and accumulate_or_finish()).
    size_t accum_size  = pad_to_full_depth ? ACCUM_DEPTH : (size_t)out_h * out_w * PE_OC;

    // Only the front sub-region (this config's real data) is filled when
    // pad_to_full_depth is set; the rest stays zero-padding that
    // conv_engine() never reads or writes, since its own loop bounds come
    // from img_h/img_w/in_ch/out_ch/k, not from how large the underlying
    // buffer happens to be.
    // PACK4: only the ifmap buffer is word-allocated - every other port
    // keeps its original element type. See pack4_words()/pack4_put() below.
    std::vector<pack4_t> x_hw(pack4_words(ifmap_size), (pack4_t)0);
    std::vector<weight_t> w_hw(weights_size, (weight_t)0);
    std::vector<bias_t> b_hw(bias_size, (bias_t)0);
    std::vector<act_t> hw_out(ofmap_size, (act_t)0);
    // Never pre-filled with reference data - accum is pure internal scratch
    // conv_engine() initializes itself (ic_tile==0 overwrites, never reads
    // stale content there); starting it at 0 like ofmap is just a
    // convenient default, not something correctness depends on.
    std::vector<accum_t> accum_hw(accum_size, (accum_t)0);

    for (size_t i = 0; i < x.size(); i++) pack4_put(x_hw, i, x[i]);
    std::copy(w.begin(), w.end(), w_hw.begin());
    std::copy(b.begin(), b.end(), b_hw.begin());

    // w_hw.data() passed twice - weights_hi is a second, independent m_axi
    // port aliasing the SAME weight data (see conv_engine.h's note on this
    // param), not a separate buffer. In real hardware, software programs
    // both address registers with the same DRAM base address; here in C-sim
    // the equivalent is simply reusing the same host-side vector.
    conv_engine(
        x_hw.data(), w_hw.data(), w_hw.data(), b_hw.data(), hw_out.data(), accum_hw.data(),
        (uint16_t)img_h, (uint16_t)img_w, (uint16_t)in_ch, (uint16_t)out_ch,
        (uint8_t)k, /*stride=*/1, (uint8_t)pad,
        requant_multiplier, (uint8_t)requant_shift, (uint8_t)(leaky_relu_enable ? 1 : 0)
    );

    unsigned mismatches = 0;
    unsigned total = out_h * out_w * out_ch;
    for (unsigned i = 0; i < total; i++) {
        int8_t hw_val = (int8_t)hw_out[i];
        int8_t ref_val = ref_out[i];
        if (hw_val != ref_val) {
            if (mismatches < 10) {
                printf("  [%s] MISMATCH at flat idx=%u: hw=%d ref=%d\n",
                       name, i, hw_val, ref_val);
            }
            mismatches++;
        }
    }

    if (mismatches == 0) {
        printf("[%s] PASS: %u output values matched the reference bit-exactly "
               "(img %ux%ux%u -> %ux%ux%u, k=%u, pad=%u)\n",
               name, total, img_w, img_h, in_ch, out_w, out_h, out_ch, k, pad);
        return 0;
    } else {
        printf("[%s] FAIL: %u/%u values mismatched\n", name, mismatches, total);
        return 1;
    }
}

// ---------------------------------------------------------------------------
// Real-layer suite (REAL_WEIGHTS_PLAN.md step 7): runs conv_engine() against
// the teammate's ACTUAL YOLOv3-tiny-ADAS weights/activations
// (real_layers_data.h, generated by python/real_layers.py from
// python_teammate/darknet_golden/), one call per real conv layer, and diffs
// directly against that layer's real expected output - NOT a call to
// reference_conv() (unlike run_config() above): `cfg.expected` already IS
// independently-verified ground truth (python/real_layers.py's own
// numpy re-implementation of conv_engine.cpp's exact math already matched
// it bit-exact for all 13 layers before these arrays were ever written -
// see REAL_WEIGHTS_PLAN.md's "STATUS" notes). A PASS here checks something
// that Python check could NOT: that conv_engine.cpp's actual synthesizable
// C++ (ap_int bit-growth/truncation, HLS pragma C-sim semantics) agrees
// with that same ground truth - not just an independent from-scratch
// re-implementation of the algorithm.
// ---------------------------------------------------------------------------
static int run_real_layer(const RealLayerCfg &cfg) {
    std::vector<pack4_t>  x_hw(pack4_words(cfg.input_size), (pack4_t)0);
    std::vector<weight_t> w_hw(cfg.weights_size, (weight_t)0);
    std::vector<bias_t>   b_hw(cfg.bias_size, (bias_t)0);
    std::vector<act_t>    hw_out(cfg.expected_size, (act_t)0);

    for (size_t i = 0; i < cfg.input_size; i++) pack4_put(x_hw, i, cfg.input[i]);
    std::copy(cfg.weights, cfg.weights + cfg.weights_size, w_hw.begin());
    std::copy(cfg.bias, cfg.bias + cfg.bias_size, b_hw.begin());

    unsigned out_h = cfg.img_h + 2 * cfg.pad - cfg.k + 1;
    unsigned out_w = cfg.img_w + 2 * cfg.pad - cfg.k + 1;
    std::vector<accum_t> accum_hw((size_t)out_h * out_w * PE_OC, (accum_t)0);

    // w_hw.data() passed twice - weights_hi is a second, independent m_axi
    // port aliasing the SAME weight data (see conv_engine.h's note on this
    // param), not a separate buffer - same as run_config() above.
    conv_engine(
        x_hw.data(), w_hw.data(), w_hw.data(), b_hw.data(), hw_out.data(), accum_hw.data(),
        (uint16_t)cfg.img_h, (uint16_t)cfg.img_w, (uint16_t)cfg.in_ch, (uint16_t)cfg.out_ch,
        (uint8_t)cfg.k, /*stride=*/1, (uint8_t)cfg.pad,
        cfg.requant_multiplier, (uint8_t)cfg.requant_shift,
        (uint8_t)(cfg.leaky_relu_enable ? 1 : 0)
    );

    unsigned mismatches = 0;
    for (size_t i = 0; i < cfg.expected_size; i++) {
        int8_t hw_val = (int8_t)hw_out[i];
        int8_t ref_val = cfg.expected[i];
        if (hw_val != ref_val) {
            if (mismatches < 10) {
                printf("  [%s] MISMATCH at flat idx=%zu: hw=%d expected=%d\n",
                       cfg.name, i, hw_val, ref_val);
            }
            mismatches++;
        }
    }

    if (mismatches == 0) {
        printf("[%s] PASS: %zu output values matched the real golden model "
               "bit-exactly (img %ux%ux%u -> %ux%ux%u, k=%u, pad=%u, leaky=%d)\n",
               cfg.name, cfg.expected_size, cfg.img_w, cfg.img_h, cfg.in_ch,
               out_w, out_h, cfg.out_ch, cfg.k, cfg.pad, cfg.leaky_relu_enable);
        return 0;
    } else {
        printf("[%s] FAIL: %u/%zu values mismatched\n", cfg.name, mismatches, cfg.expected_size);
        return 1;
    }
}

// Cosim-safe variant of run_real_layer() above: pads host buffers out to the
// FULL m_axi depth (IFMAP_DEPTH etc.) instead of this layer's real (much
// smaller) size, exactly like run_config()'s pad_to_full_depth path - for
// the same reason (cosim's RTL bus-functional model is sized from the
// m_axi `depth=` pragma, not from the call's real dimensions; see this
// project's TROUBLESHOOTING.md, the ENTER_WRAPC/SIGSEGV entry). Lets ONE
// REAL network layer - real shape, real weights, real golden-model expected
// output, not the synthetic 16x16x3 config-A-cosim shape - run through
// C/RTL co-simulation, so a real per-layer cycle count / delivered-MACs
// figure can be measured instead of guessed (RESOURCE_BUDGET.md §6 item 3 /
// doc/plan_no_board_verification_and_perf.md P1).
static int run_real_layer_cosim(const RealLayerCfg &cfg) {
    std::vector<pack4_t>  x_hw(pack4_words(IFMAP_DEPTH), (pack4_t)0);
    std::vector<weight_t> w_hw(WEIGHTS_DEPTH, (weight_t)0);
    std::vector<bias_t>   b_hw(BIAS_DEPTH,    (bias_t)0);
    std::vector<act_t>    hw_out(OFMAP_DEPTH, (act_t)0);
    std::vector<accum_t>  accum_hw(ACCUM_DEPTH, (accum_t)0);

    for (size_t i = 0; i < cfg.input_size; i++) pack4_put(x_hw, i, cfg.input[i]);
    std::copy(cfg.weights, cfg.weights + cfg.weights_size, w_hw.begin());
    std::copy(cfg.bias,    cfg.bias    + cfg.bias_size,    b_hw.begin());

    // w_hw.data() passed twice - weights_hi aliases the same weight data,
    // same as run_config()/run_real_layer() above.
    conv_engine(
        x_hw.data(), w_hw.data(), w_hw.data(), b_hw.data(), hw_out.data(), accum_hw.data(),
        (uint16_t)cfg.img_h, (uint16_t)cfg.img_w, (uint16_t)cfg.in_ch, (uint16_t)cfg.out_ch,
        (uint8_t)cfg.k, /*stride=*/1, (uint8_t)cfg.pad,
        cfg.requant_multiplier, (uint8_t)cfg.requant_shift,
        (uint8_t)(cfg.leaky_relu_enable ? 1 : 0)
    );

    unsigned out_h = cfg.img_h + 2 * cfg.pad - cfg.k + 1;
    unsigned out_w = cfg.img_w + 2 * cfg.pad - cfg.k + 1;
    unsigned mismatches = 0;
    for (size_t i = 0; i < cfg.expected_size; i++) {
        int8_t hw_val = (int8_t)hw_out[i];
        int8_t ref_val = cfg.expected[i];
        if (hw_val != ref_val) {
            if (mismatches < 10) {
                printf("  [%s] MISMATCH at flat idx=%zu: hw=%d expected=%d\n",
                       cfg.name, i, hw_val, ref_val);
            }
            mismatches++;
        }
    }

    if (mismatches == 0) {
        printf("[%s] COSIM-REAL PASS: %zu output values matched the real "
               "golden model bit-exactly (img %ux%ux%u -> %ux%ux%u, k=%u, "
               "pad=%u)\n", cfg.name, cfg.expected_size, cfg.img_w, cfg.img_h,
               cfg.in_ch, out_w, out_h, cfg.out_ch, cfg.k, cfg.pad);
        return 0;
    } else {
        printf("[%s] COSIM-REAL FAIL: %u/%zu values mismatched\n",
               cfg.name, mismatches, cfg.expected_size);
        return 1;
    }
}

int main(int argc, char **argv) {
    // C/RTL co-simulation runs this same compiled testbench, but
    // `cosim_design` RTL-simulates the FIRST call made to the top-level
    // function (conv_engine), not just the specific call intended for it.
    // Configs A-H below all use small, non-full-depth host buffers (see the
    // pad_to_full_depth comment on IFMAP_DEPTH etc.) - fine for plain C-sim,
    // which never reads `depth`, but fatal for cosim: its RTL bus-functional
    // model is sized from the m_axi `depth=` pragma, so reading config-A's
    // small buffer as if it were that large SIGSEGVs during ENTER_WRAPC.
    // run_hls.tcl passes --cosim-only to `cosim_design -argv`, so cosim only
    // ever reaches config-A-cosim (the one call sized with
    // pad_to_full_depth=true) as the first and only conv_engine() call.
    //
    // Optional 2nd argv: a REAL_LAYERS[] index (0-12) - when present, cosim
    // runs run_real_layer_cosim() on that real layer instead of the
    // synthetic config-A-cosim shape (see that function's comment on why -
    // measuring real per-layer cycle counts instead of guessing efficiency,
    // doc/plan_no_board_verification_and_perf.md P1). run_hls.tcl passes
    // this through from the RUN_HLS_COSIM_LAYER environment variable.
    // Absent (default): behavior is unchanged from before this option
    // existed - the synthetic config-A-cosim shape runs, same as always.
    bool cosim_only = (argc > 1 && std::strcmp(argv[1], "--cosim-only") == 0);
    int cosim_real_layer = -1;
    if (cosim_only && argc > 2) {
        cosim_real_layer = std::atoi(argv[2]);
        if (cosim_real_layer < 0 || cosim_real_layer >= NUM_REAL_LAYERS) {
            printf("--cosim-only: layer index %d out of range [0,%d), ignoring - "
                   "falling back to the synthetic config-A-cosim shape\n",
                   cosim_real_layer, NUM_REAL_LAYERS);
            cosim_real_layer = -1;
        }
    }

    // Correctness gate for the INT8 DSP-packing primitive itself - run
    // before anything else. An assert() failure here aborts the whole
    // binary, which is intentional: there's no point running the 8 configs
    // below against a packing primitive already proven wrong.
    pack_unpack_selftest_fast();
    pack_unpack_selftest_ap_int_sample();

    int fail = 0;

    // Real layer-0 values from the teammate's YOLOv3-tiny-ADAS golden model
    // (python_teammate/darknet_golden/artifacts/int8/model_manifest.json,
    // layer index 0) - not arbitrary placeholders, so passing this exact
    // pair through conv_engine() and reference_conv() actually exercises
    // the requantization path against a value it will really see, not just
    // an easy round number.
    const int32_t LAYER0_MULTIPLIER = 1264723901;
    const unsigned LAYER0_SHIFT = 37;

    if (cosim_only) {
        if (cosim_real_layer >= 0) {
            fail = run_real_layer_cosim(REAL_LAYERS[cosim_real_layer]);
        } else {
            fail = run_config("config-A-cosim: same as config-A, full m_axi depth",
                               /*img_h=*/16, /*img_w=*/16, /*in_ch=*/3,
                               /*out_ch=*/16, /*k=*/3, /*pad=*/1, /*seed=*/42,
                               /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT,
                               /*pad_to_full_depth=*/true);
        }
        if (!fail) {
            printf("COSIM CONFIG PASS\n");
            return 0;
        }
        printf("COSIM CONFIG FAILED\n");
        return 1;
    }

    // Config A: small stand-in for conv_layer1's shape (3->16 channels, k=3,
    // "same" padding), sized down so C-sim runs fast. out_ch=16 == PE_OC
    // exactly - exactly one, exactly-full output-channel tile.
    fail |= run_config("config-A: baseline (out_ch == PE_OC)",
                        /*img_h=*/16, /*img_w=*/16, /*in_ch=*/3,
                        /*out_ch=*/16, /*k=*/3, /*pad=*/1, /*seed=*/42,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT);

    // Config B: out_ch=30 > PE_OC=20 and NOT a multiple of it - this is the
    // case that actually exercises the OC_TILE loop running MORE THAN ONCE
    // (2 tiles: one full 20-wide tile, one partial 10-wide tile). A smaller
    // out_ch than PE_OC produces only a single partial tile and never
    // reaches the "am I correctly resuming for tile 2" case at all - that
    // gap is exactly the kind of thing that's easy to miss when a
    // resource-budget change quietly invalidates what an old test was
    // actually covering. Caught exactly this happening here: this config
    // used out_ch=20 when PE_OC was 16 (2 tiles: 16 full + 4 partial), but
    // after PE_OC's post-packing increase to 20 (RESOURCE_BUDGET.md §5),
    // out_ch=20 became a single *exactly-full* tile - still a real edge case
    // (now covered by config-A instead, where out_ch==PE_OC exactly), but no
    // longer the multi-tile case this config's own name and comment claimed.
    // Bumped to 30 to restore actual multi-tile coverage - also the config
    // that would show whether OC_TILE's weight-tile double buffering
    // (conv_engine.cpp's DATAFLOW, RESOURCE_BUDGET.md §5) is doing anything:
    // with only 1 tile, tile-to-tile overlap has nothing to overlap with.
    fail |= run_config("config-B: multi-tile, non-multiple out_ch",
                        /*img_h=*/10, /*img_w=*/10, /*in_ch=*/5,
                        /*out_ch=*/30, /*k=*/3, /*pad=*/1, /*seed=*/7,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT);

    // Config C: 1x1 convolution (k=1, pad=0) - the detection-head layer
    // shape in YOLO-style networks. Exercises k-1=0 everywhere the raster
    // scan's window-fill logic subtracts (k-1) or loops to (k-2); those are
    // exactly the lines most likely to have an off-by-one for k=1 that
    // config A/B (both k=3) cannot catch.
    // Uses layer-15's real manifest values instead of layer-0's: layer 15 is
    // the actual detection-head 1x1 conv (activation="linear", per
    // RTL_HANDOFF_KO.md section 7), so leaky_relu_enable=false here also
    // exercises the "skip LeakyReLU entirely" branch that no other config
    // below does.
    fail |= run_config("config-C: 1x1 conv (k=1, pad=0), linear head activation",
                        /*img_h=*/8, /*img_w=*/8, /*in_ch=*/4,
                        /*out_ch=*/3, /*k=*/1, /*pad=*/0, /*seed=*/11,
                        /*leaky_relu_enable=*/false, /*requant_multiplier=*/1576269802,
                        /*requant_shift=*/42);

    // Config D: minimal channel counts (in_ch=1, out_ch=1) - degenerate
    // case for the TR=16-wide reduction unroll (only 1 of 16 lanes ever has
    // real data) and for PE_LOOP (only 1 of PE_OC=16 lanes active).
    fail |= run_config("config-D: minimal channels (in_ch=1, out_ch=1)",
                        /*img_h=*/6, /*img_w=*/6, /*in_ch=*/1,
                        /*out_ch=*/1, /*k=*/3, /*pad=*/1, /*seed=*/13,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT);

    // Config E: in_ch=MAX_IN_CH exactly (128) - now just the boundary where
    // num_ic_tiles is still exactly 1 (single on-chip tile, no `accum` DDR
    // traffic at all - see accumulate_or_finish()), not an upper bound on
    // what conv_engine() can run at all anymore (input-channel tiling
    // handles in_ch up to MAX_TOTAL_IN_CH now - see configs I/J/K below for
    // the case where it doesn't fit in one tile). Also in_ch=128 is an
    // exact multiple of TR=16 (8 full reduction tiles, no remainder) -
    // paired with config F below (a non-multiple) for reduction-tiling
    // coverage.
    fail |= run_config("config-E: in_ch == MAX_IN_CH boundary (128, TR-aligned)",
                        /*img_h=*/4, /*img_w=*/4, /*in_ch=*/MAX_IN_CH,
                        /*out_ch=*/8, /*k=*/3, /*pad=*/1, /*seed=*/17,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT);

    // Config F: in_ch=20 is NOT a multiple of TR=16 (1 full reduction tile
    // of 16 + a remainder of 4) - checks the MAC_IC UNROLL factor=TR loop's
    // automatic remainder handling on a runtime-bounded trip count, which
    // config E's clean 128/16 split never exercises.
    fail |= run_config("config-F: in_ch not a multiple of TR (20)",
                        /*img_h=*/6, /*img_w=*/6, /*in_ch=*/20,
                        /*out_ch=*/5, /*k=*/3, /*pad=*/1, /*seed=*/19,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT);

    // Config G: non-square image (img_h != img_w) - catches any place H/W
    // might have been silently swapped or assumed equal.
    fail |= run_config("config-G: non-square image",
                        /*img_h=*/12, /*img_w=*/7, /*in_ch=*/4,
                        /*out_ch=*/6, /*k=*/3, /*pad=*/1, /*seed=*/23,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT);

    // Config H: added specifically for the INT8 DSP MAC-pairing change
    // (RESOURCE_BUDGET.md §5) - exercises a pe-pair straddling the out_ch
    // validity boundary AFTER a preceding FULL tile. out_ch=17: tile0 (oc
    // 0-15, 16 valid channels, EVEN - every pair fully valid, no straddle)
    // then tile1 (oc 16 only, 1 valid channel, ODD - pair j=0 of tile1 has
    // lo=oc16 VALID, hi=oc17 INVALID, so the shared multiply still runs for
    // both halves but only acc_lo's result gets written to ofmap). Configs
    // C/D/F above incidentally already have odd out_ch (a same-tile
    // straddle), but relying on that is fragile if those sizes ever change
    // for unrelated reasons, and none of them combine a straddle with a
    // preceding full tile the way this one does.
    fail |= run_config("config-H: out_ch straddles a pe-pair boundary (17)",
                        /*img_h=*/6, /*img_w=*/6, /*in_ch=*/6,
                        /*out_ch=*/17, /*k=*/3, /*pad=*/1, /*seed=*/29,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT);

    // Config I: in_ch=MAX_IN_CH+1 (129) - the SMALLEST case that actually
    // triggers 2 ic_tiles (one full 128-wide tile, one 1-wide remainder).
    // None of configs A-H ever exceed MAX_IN_CH, so this is the first config
    // where num_ic_tiles > 1 at all, exercising accumulate_or_finish()'s
    // accum-DDR read-modify-write path and its remainder handling for the
    // first time (added once the real network showed 8 of 13 conv layers
    // need this - see conv_engine.h).
    fail |= run_config("config-I: in_ch=MAX_IN_CH+1 (129), 2 ic_tiles w/ remainder",
                        /*img_h=*/4, /*img_w=*/4, /*in_ch=*/MAX_IN_CH + 1,
                        /*out_ch=*/4, /*k=*/3, /*pad=*/1, /*seed=*/31,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT);

    // Config J: in_ch=2*MAX_IN_CH (256) - exactly 2 full ic_tiles, no
    // remainder. Paired with config I the same way config E/F pair for the
    // TR axis (aligned vs. non-aligned).
    fail |= run_config("config-J: in_ch=2*MAX_IN_CH (256), 2 exact ic_tiles",
                        /*img_h=*/4, /*img_w=*/4, /*in_ch=*/2 * MAX_IN_CH,
                        /*out_ch=*/4, /*k=*/3, /*pad=*/1, /*seed=*/37,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT);

    // Config K: BOTH axes multi-pass at once (out_ch=25 -> 2 oc_tiles;
    // in_ch=150 -> 2 ic_tiles) - the real network's layer 13 (in_ch=1024,
    // out_ch=256) is exactly this combination, just scaled down here to
    // keep C-sim fast. This is the one config that can actually catch a bug
    // in `accum`'s per-oc_tile reuse (conv_engine.h's note on why it's
    // sized [out_h][out_w][PE_OC], not [out_h][out_w][out_ch]) - e.g. stale
    // data leaking from oc_tile 0 into oc_tile 1's ic_tile 0 pass - since
    // that requires more than one oc_tile to even be possible, and configs
    // I/J above only ever have a single oc_tile.
    fail |= run_config("config-K: both oc_tile and ic_tile multi-pass",
                        /*img_h=*/3, /*img_w=*/3, /*in_ch=*/150,
                        /*out_ch=*/25, /*k=*/3, /*pad=*/1, /*seed=*/41,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT);

    // Cosim smoke test: same shape as config-A, but with pad_to_full_depth
    // set so C/RTL co-simulation's RTL bus-functional-model memory image
    // (built from the m_axi `depth=` pragmas, not from this call's actual
    // small dimensions) doesn't read past the end of the host arrays -
    // see the comment on IFMAP_DEPTH etc. above and TROUBLESHOOTING.md's
    // cosim entry. Deliberately just ONE config, not all 8 - cosim's job
    // here is checking the tool's C-to-RTL translation on a representative
    // case, not re-proving algorithm correctness across edge cases (the 8
    // configs above already do that, fast, via C-sim). Running all 8 at
    // full depth was tried first and made ordinary C-sim itself far too
    // slow, since C-sim never needed full depth in the first place.
    fail |= run_config("config-A-cosim: same as config-A, full m_axi depth",
                        /*img_h=*/16, /*img_w=*/16, /*in_ch=*/3,
                        /*out_ch=*/16, /*k=*/3, /*pad=*/1, /*seed=*/42,
                        /*leaky_relu_enable=*/true, LAYER0_MULTIPLIER, LAYER0_SHIFT,
                        /*pad_to_full_depth=*/true);

    // Real-layer suite (REAL_WEIGHTS_PLAN.md step 7) - the teammate's actual
    // 13 real conv layers (real_layers_data.h), not synthetic edge cases.
    // Kept as a separate pass/fail tally (own "ALL REAL LAYERS PASS" line)
    // so a failure here is distinguishable at a glance from a synthetic
    // config regression, even though both fold into the same overall `fail`
    // / "ALL CONFIGS PASS" result run_hls.bat's log parsing already checks
    // for - no build-script change needed to pick this suite up.
    int real_fail = 0;
    for (unsigned i = 0; i < NUM_REAL_LAYERS; i++) {
        real_fail |= run_real_layer(REAL_LAYERS[i]);
    }
    printf(real_fail ? "ONE OR MORE REAL LAYERS FAILED\n" : "ALL REAL LAYERS PASS\n");
    fail |= real_fail;

    if (!fail) {
        printf("ALL CONFIGS PASS\n");
        return 0;
    }
    printf("ONE OR MORE CONFIGS FAILED\n");
    return 1;
}

// ---------------------------------------------------------------------------
// NOT covered by this automated suite, and deliberately so - see
// RESOURCE_BUDGET.md and conv_engine.h "design limits":
//
//   - stride != 1: conv_engine() asserts stride==1 (see conv_engine.cpp).
//     Confirming that assertion actually fires is a manual negative test
//     (calling conv_engine() with stride=2 and confirming the program
//     aborts) - not automated here because a failing assert() terminates
//     the whole test binary, which would stop config G etc. from ever
//     running in the same executable.
//   - in_ch > MAX_TOTAL_IN_CH: same reasoning - asserts and aborts, checked
//     manually, not part of the automated pass/fail sequence above. NOTE:
//     in_ch > MAX_IN_CH alone is NOT this case anymore - input-channel
//     tiling (configs I/J/K above) handles that correctly now.
// ---------------------------------------------------------------------------
